/**:
  ros__parameters:
    base_frame_id: "base_link"

    expected_control_cmd_hz: 33.0
    expected_gear_cmd_hz: 0.0
    expected_vehicle_emergency_cmd_hz: 33.0
    expected_vcu_stat_motion_hz: 0.0
    expected_vcu_stat_vehicle_state_hz: 0.0